version: "3"

services:

  db:
      image: postgres:alpine
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pw
        POSTGRES_DB: todo_db
        PGDATA: /data/postgres
      container_name: postgres_container
      volumes:
         - postgres:/data/postgres
      networks:
        - project_network
      ports:
        - "5432:5432"
      restart: unless-stopped


  mainapi:
      container_name: mainapi_container
      image: todo_image
      build: .
      volumes:
        - .:/source/todo/
      ports:
        - "8123:8123"
      networks:
        - project_network
      depends_on:
        - db
      links:
        - db
      environment:
        DB_HOST: db
        DB_USER: user
        DB_PW: pw
        DB_NAME: todo_db
      command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8123
      restart: "always"

volumes:
  postgres:

networks:
  project_network:
